import {
  BUILTIN_TOOL_KEY_SET,
  resolveBuiltinToolEnabled,
} from "./catalog";
import { BUILTIN_TOOLKIT_RUNTIME_REGISTRY } from "./registry";

const CHATROOM_TOOL_NAMES = [
  "create_chat_room",
  "close_chat_room",
  "reopen_chat_room",
] as const;

const CODE_EXECUTION_TOOL_NAMES = [
  "run_python_code",
  "run_javascript_code",
  "run_html_preview",
] as const;

type ToolsConfigLike = Record<string, unknown> | null | undefined;

interface ResolveBuiltinToolAccessParams<T extends Record<string, unknown>> {
  builtinTools: T;
  toolsConfig: ToolsConfigLike;
  hasEmbeddingApiKey: boolean;
  hasImageInput: boolean;
  configuredKnowledgeEmbedModel?: string | null;
  logger?: (message: string) => void;
}

function hasTool(toolNames: Set<string>, toolName: string): boolean {
  return toolNames.has(toolName);
}

export function resolveEnabledBuiltinTools<T extends Record<string, unknown>>({
  builtinTools,
  toolsConfig,
  hasEmbeddingApiKey,
  hasImageInput,
  configuredKnowledgeEmbedModel,
  logger,
}: ResolveBuiltinToolAccessParams<T>): T {
  const filteredBuiltin = {} as T;

  for (const [toolName, definition] of Object.entries(builtinTools)) {
    if (!BUILTIN_TOOL_KEY_SET.has(toolName)) {
      (filteredBuiltin as Record<string, unknown>)[toolName] = definition;
      continue;
    }

    if (resolveBuiltinToolEnabled(toolsConfig, toolName)) {
      (filteredBuiltin as Record<string, unknown>)[toolName] = definition;
    }
  }

  if (!hasEmbeddingApiKey && "knowledge_search" in (filteredBuiltin as Record<string, unknown>)) {
    delete (filteredBuiltin as Record<string, unknown>).knowledge_search;
    logger?.("knowledge_search tool disabled: missing EMBEDDING_API_KEY");
  }

  const canImageKnowledgeSearchByModel = configuredKnowledgeEmbedModel === "gemini-embedding-2-preview";
  if (
    hasImageInput &&
    !canImageKnowledgeSearchByModel &&
    "knowledge_search" in (filteredBuiltin as Record<string, unknown>)
  ) {
    delete (filteredBuiltin as Record<string, unknown>).knowledge_search;
    logger?.(
      `knowledge_search tool disabled for image input (knowledge_embed_model=${configuredKnowledgeEmbedModel ?? "unset"})`,
    );
  }

  return filteredBuiltin;
}

export function buildToolPolicySections(params: {
  availableToolNames: Iterable<string>;
}): string[] {
  const toolNames = new Set(params.availableToolNames);
  const sections: string[] = [];

  if (CHATROOM_TOOL_NAMES.some((toolName) => hasTool(toolNames, toolName))) {
    sections.push(
      "## Chatroom Tool Policy\n" +
      "- If user asks to create/open/start a room/chatroom, you MUST call `create_chat_room`.\n" +
      "- If user asks to close a room/chatroom, you MUST call `close_chat_room`.\n" +
      "- If user asks to reopen/restart a closed room/chatroom, you MUST call `reopen_chat_room`.\n" +
      "- Never generate HTML prototypes or fake links for chatroom requests.\n" +
      "- Never call `run_html_preview` for chatroom creation requests.\n" +
      "- After a room tool succeeds, do not invent additional links or duplicate invitations.",
    );
  }

  const codeToolNames = CODE_EXECUTION_TOOL_NAMES.filter((toolName) => hasTool(toolNames, toolName));
  if (codeToolNames.length > 0) {
    sections.push(
      "## Code Execution Tool Policy\n" +
      "You have access to secure cloud sandboxes for running code. Follow these rules:\n" +
      (codeToolNames.includes("run_python_code")
        ? "- When the user asks you to run/execute Python code, generate charts, do data analysis, or anything that requires Python execution, you MUST call `run_python_code` to actually run the code. NEVER just paste code as text — the user expects real execution results.\n" +
          "- Charts generated by matplotlib/seaborn are returned as base64 PNG in the tool result. Images are automatically sent to the user — do NOT embed base64 strings in your text reply. Just describe the chart and reference the execution results.\n"
        : "") +
      (codeToolNames.includes("run_javascript_code")
        ? "- When the user asks you to run/execute JavaScript or Node.js code, you MUST call `run_javascript_code`.\n"
        : "") +
      (codeToolNames.includes("run_html_preview")
        ? "- When the user asks you to create/preview HTML pages, landing pages, or web UI, you MUST call `run_html_preview` to generate a shareable preview link. NEVER output raw HTML as text — the user needs a clickable URL.\n"
        : "") +
      "- NEVER fabricate URLs, image links, or file paths. Only return URLs that tools actually provide.\n" +
      "- If a tool call fails, report the error honestly instead of faking a result.",
    );
  } else {
    sections.push(
      "## Important: No Code Execution Capability\n" +
      "You do NOT have code execution tools enabled. " +
      "If the user asks you to run code, generate charts, execute scripts, or create HTML previews, " +
      "you MUST honestly tell them that the code execution feature is not enabled for this agent, " +
      "and suggest the admin enable it in Dashboard > Agents > Tool Settings. " +
      "NEVER pretend you have executed code. NEVER fabricate execution results, images, charts, or URLs. " +
      "You may still write code snippets as text for the user to run themselves.",
    );
  }

  for (const toolkit of BUILTIN_TOOLKIT_RUNTIME_REGISTRY) {
    const section = toolkit.buildPolicySection?.({ availableToolNames: toolNames }) ?? null;
    if (section) sections.push(section);
  }

  if (hasTool(toolNames, "image_generate")) {
    sections.push(
      "## Image Generation & Editing Tool Policy\n" +
      "You have access to `image_generate` which supports two modes:\n" +
      "### Text-to-Image\n" +
      "- When the user asks to generate, create, draw, or design an image, call `image_generate` with only `prompt`.\n" +
      "### Image Editing\n" +
      "- When the user sends an image AND asks to modify/edit it (add elements, remove objects, change style, adjust colors, etc.), call `image_generate` with `prompt` describing the desired edit, plus `source_image_base64` containing the user's image data.\n" +
      "- If the user's image was provided in the conversation as a base64 image, extract its data for `source_image_base64` and set `source_mime_type` accordingly.\n" +
      "### General Rules\n" +
      "- Always craft detailed, descriptive prompts in English for best results, even if the user writes in another language.\n" +
      "- The generated/edited image will be automatically sent to the user — do NOT embed base64 strings in your text reply.\n" +
      "- NEVER fabricate image URLs or claim images were generated without calling the tool.\n" +
      "- If the tool call fails, report the error honestly instead of faking a result.",
    );
  }

  return sections;
}

export function resolveGenerateTextToolDirective(params: {
  availableToolNames: Iterable<string>;
  messageText: string;
}): { activeTools: string[]; toolChoice?: "required" } | null {
  const toolNames = new Set(params.availableToolNames);
  const activeTools = new Set<string>();
  let toolChoice: "required" | undefined;

  for (const toolkit of BUILTIN_TOOLKIT_RUNTIME_REGISTRY) {
    const directive = toolkit.getGenerateTextDirective?.({
      availableToolNames: toolNames,
      messageText: params.messageText,
    });
    if (!directive) continue;

    for (const toolName of directive.activeTools) {
      if (toolNames.has(toolName)) activeTools.add(toolName);
    }
    if (directive.toolChoice === "required") {
      toolChoice = "required";
    }
  }

  if (activeTools.size === 0) return null;

  return {
    activeTools: [...activeTools],
    ...(toolChoice ? { toolChoice } : {}),
  };
}
